;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-indent-just-newline
        evil-backward-char
        evil-destroy-change
        evil-normal-state
        evil-previous-line
        elscreen-previous
        evil-backward-char
        evil-change
        evil-delete-backward-char-and-join
        evil-exit-visual-state
        evil-forward-word-begin
        evil-insert
        evil-next-line
        evil-normal-state
        ns-copy-including-secondary
        sp--self-insert-command
        yank-and-indent
        ))

(setq mc/cmds-to-run-once
      '(
        helm-projectile
        ))
