(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(aquamacs-additional-fontsets nil t)
 '(aquamacs-customization-version-id 305 t)
 '(aquamacs-tool-bar-user-customization nil t)
 '(custom-enabled-themes (quote (tango-dark)))
 '(default-frame-alist
    (quote
     ((cursor-type . box)
      (internal-border-width . 0)
      (background-toolbar-color . "#cf3ccf3ccf3c")
      (bottom-toolbar-shadow-color . "#79e77df779e7")
      (top-toolbar-shadow-color . "#fffffbeeffff")
      (viper-saved-cursor-color-in-replace-mode . "Red3")
      (border-color . "black")
      (color-theme-name . color-theme-jsc-dark)
      (modeline . t)
      (fringe)
      (mouse-color . "black")
      (cursor-color . "#fce94f")
      (background-mode . dark)
      (tool-bar-lines . 0)
      (menu-bar-lines . 1)
      (right-fringe . 12)
      (left-fringe . 4)
      (background-color . "#2e3436")
      (foreground-color . "gray100")
      (font . "-*-Menlo-normal-normal-normal-*-14-*-*-*-m-0-iso10646-1")
      (fontsize . 0)
      (font-backend mac-ct ns))))
 '(fci-rule-color "#383838")
 '(global-linum-mode t)
 '(highlight-symbol-on-navigation-p nil)
 '(ns-command-modifier (quote super))
 '(ns-tool-bar-display-mode nil t)
 '(ns-tool-bar-size-mode nil t)
 '(one-buffer-one-frame-mode nil nil (aquamacs-frame-setup))
 '(tabbar-mode t nil (tabbar))
 '(tree-widget-image-enable nil)
 '(visual-line-mode nil t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#2e3436" :foreground "gray100" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "nil" :family "Menlo"))))
 '(elscreen-tab-background-face ((t (:background "#2e3436"))) t)
 '(elscreen-tab-other-screen-face ((t (:background "gray66" :foreground "black" :underline t))) t)
 '(font-lock-builtin-face ((t (:foreground "light sky blue"))))
 '(font-lock-comment-face ((t (:foreground "gray43"))))
 '(font-lock-string-face ((t (:foreground "yellow green"))))
 '(helm-selection ((t (:foreground "Green"))))
 '(helm-source-header ((t (:foreground "white" :weight bold))))
 '(highlight-symbol-face ((t (:background "gray30"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "gray100"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "orange1"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "purple1"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "OrangeRed1"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "OliveDrab3"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "cyan1"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "SteelBlue1"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "salmon"))))
 '(region ((t (:background "gray50"))))
 '(sp-pair-overlay-face ((t (:inherit default))))
 '(sp-wrap-overlay-face ((t nil)))
 '(sp-wrap-tag-overlay-face ((t nil))))
